input: data/interim/annotations/b988e66d1542430cbc6e703be781e49c_isdb_pretreated.tsv.gz
output: data/interim/annotations/b988e66d1542430cbc6e703be781e49c_isdb_filled.tsv.gz
tool: gnps ## or manual
components: ## if manual 
gnps: b988e66d1542430cbc6e703be781e49c
mode: pos