image: continuumio/miniconda3:latest

stages:
  - integration
  - deploy

integration-test:
  stage: integration
  script:
    - conda env create -f environment.yml
    - bash tests/integration_test.sh

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r docs .public
    - mv .public public
  artifacts:
    paths:
      - docs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - changes:
      - .gitlab-ci.yml
      - DESCRIPTION
      - docs
      - LICENSE.md
      - logo.svg
      - man
      - pkgdown
      - vignettes
