version: "3.9"

services:
  prepare_params:
    build: "."
    image: adafede/tima-r
    volumes:
      - "./config:/config"
    command: Rscript inst/scripts/prepare_params.R

  tima:
    build: "."
    image: adafede/tima-r
    volumes:
      - "./config:/config"
      - "./inst:/inst"
      - ".data:/data"
    command: Rscript inst/scripts/tima_full.R

# other smaller services not implemented yet