name: tima
channels:
  - conda-forge
  - defaults
dependencies:
  - curl
  - r-base>=4.1.0
  - r-crayon
  - r-data.table
  - r-docopt
  - r-dplyr
  - r-jsonlite
  - r-purrr
  - r-readr
  - r-R.utils
  - r-splitstackshape
  - r-stringr
  - r-tidyr
  - r-yaml
