on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tima-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"      
      - name: Install dependencies
        run: |
          conda env create -q --file environment.yml
      - name: Run tests
        run: |
          bash tests/integration_test.sh
          
  tima-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"  
      - name: Install dependencies
        run: |
          conda env create -q --file environment.yml
      - name: Run tests
        run: |
          bash tests/integration_test.sh
