name: External Use

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  tima-test:
    name: tima-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - if: matrix.os == 'windows-latest'
        uses: Vampire/setup-wsl@v1.1.0
        with:
          additional-packages:
            curl
            dos2unix
            gzip
            unzip
            wget
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          mamba-version: "*"
          channels: conda-forge, bioconda, defaults
          channel-priority: true
          activate-environment: base
          environment-file: environment.yml
      - uses: s-weigand/setup-conda@v1
      - name: Run tests (unix)
        if: matrix.os != 'windows-latest'
        run: |
           bash tests/integration_test.sh
      - name: Run tests (windows)
        if: matrix.os == 'windows-latest'
        run: |
          git rm --cached -r .
          git reset --hard
          wsl bash tests/integration_test.sh
