name: External Use

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tima-test:
    name: tima-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - if: matrix.os == 'windows-latest'
        run: |
          choco install curl
          choco install gzip
          choco install unzip
          choco install wget
      - name: Run install
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e 'if(!require(remotes)){install.packages("remotes")}
          remotes::install_github("taxonomicallyinformedannotation/tima-r")'
      - name: Run tests
        run: |
          bash tests/integration_test.sh
