name: External Use

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tima-test:
    name: tima-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 
          'ubuntu-latest', 
          'macos-latest', 
          'windows-latest'
        ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-r-dependencies@v1
      - name: Run tests
        run: |
          cp -R config/default config/params
          Rscript inst/scripts/tima.R
