name: External Use

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  tima-test:
    name: tima-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          mamba-version: "*"
          channels: conda-forge, bioconda, defaults
          channel-priority: true
          activate-environment: tima
          environment-file: environment.yml
      - name: Setup WSL
        if: matrix.os == 'windows-latest'
        uses: Vampire/setup-wsl@v1.1.0
      - name: Install Windows specific dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install curl
          choco install gzip
          choco install unzip
          choco install wget
      - name: Run tests
        shell: bash -l {0}
        run: |
          bash tests/integration_test.sh
