on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tima-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: wsl-bash {0}
        
    steps:
    - uses: Vampire/setup-wsl@v1
    
    - run: |
          npm ci
          npm run build
          npm run package
