on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tima-windows:
    runs-on: windows-latest
    steps:
      - name: Enable WSL
        run: |
          Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
          Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          wsl conda env create --file environment.yml
      - name: Run tests
        run: |
          wsl bash tests/integration_test.sh
