on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tima-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"      
      - name: Install dependencies
        run: |
          conda env create --file environment.yml
      - name: Run tests
        run: |
          bash tests/integration_test.sh
          
  tima-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"  
      - name: Install dependencies
        run: |
          conda env create --file environment.yml
      - name: Run tests
        run: |
          bash tests/integration_test.sh
          
  tima-windows:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"  
      - name: Setup WSL
        run: |
          $url = "https://aka.ms/wsl-ubuntu-1804"
          $output = ".\Ubuntu.zip"
          (New-Object System.Net.WebClient).DownloadFile($url, $output)
          Expand-Archive .\Ubuntu.zip .\Ubuntu
          Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
          .\Ubuntu\ubuntu1804.exe install --root
          wsl -u root -d Ubuntu-18.04 wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
          wsl -u root -d Ubuntu-18.04 bash Miniconda3-latest-Linux-x86_64.sh -b
          wsl -u root -d Ubuntu-18.04 source ~/.bashrc
          wsl -u root -d Ubuntu-18.04 export PATH=/home/USER/anaconda3/bin:$PATH
          wsl -u root -d Ubuntu-18.04 conda init
      - name: Install dependencies
        run: |
          wsl -u root -d Ubuntu-18.04 conda env create --file environment.yml
      - name: Run tests
        run: |
          wsl -u root -d Ubuntu-18.04 bash tests/integration_test.sh
          
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
